src/main/scala/scodec/codecs/TupleCodec.scala, src/main/scala/scodec/package.scala, src/test/scala/scodec/codecs/TupleCodecTest.scala
add support for easliy creating codecs for case classes going through tuples but withotu shapeless
=> case class support with using shapeless

src/main/scala/scodec/codecs/ChecksumCodec.scala, src/main/scala/scodec/codecs/package.scala, src/test/scala/scodec/codecs/ChecksumCodecTest.scala
https://groups.google.com/forum/#!topic/typelevel/jSLznFshLXU
=> added ChecksumCodec (verifies checksum before delegating)

src/main/scala/scodec/codecs/MultiplexedCodec.scala, src/main/scala/scodec/codecs/package.scala, src/test/scala/scodec/codecs/MultiplexedCodecTest.scala
Added support for codecs for delimited collections using a generalized MultiplexedCodec.
=> Added MultiplexedCodec (and support for delimited collections)

src/main/scala/scodec/codecs/package.scala, src/test/scala/scodec/codecs/StringCodecTest.scala
Could still be pushed into its own class.
=> adds cstring codec for null terminated ascii strings

shared/src/main/scala/scodec/codecs/ConstrainedVariableSizeCodec.scala, shared/src/main/scala/scodec/codecs/package.scala, shared/src/test/scala/scodec/codecs/ConstrainedVariableSizeCodecTest.scala
Implementation of a Base Codec that allows constraints on minimum and maximum sizes.
The size is still variable within this range.
=> Size constrained variable

shared/src/main/scala/scodec/codecs/ZlibCodec.scala
=> Make zlib codec return remaining bits

build.sbt, project/build.properties
ref. https://github.com/typelevel/scala/issues/135
=> update sbt.version to 0.13.13; switch to CrossVersion.patch

shared/src/main/scala/scodec/codecs/FixedSizeStrictCodec.scala, shared/src/main/scala/scodec/codecs/package.scala, shared/src/test/scala/scodec/codecs/BytesCodecTest.scala, shared/src/test/scala/scodec/codecs/BytesStrictCodecTest.scala
=> Added bitsStrict/bytesStrict codecs, fixed doc on bits/bytes codecs

shared/src/main/scala/scodec/codecs/VariableSizeDelimitedCodec.scala, shared/src/main/scala/scodec/codecs/package.scala, unitTests/src/test/scala/scodec/codecs/VariableSizeDelimitedCodecTest.scala
=> Add variable size delimited codec

README.md
i forked this library from yzernik. his library is not maintained and is missing a lot of new messages that have been introduced since then. I also added support for both Bitcoin Cash and Core networks. I'm currently maintaining and using this library.
=> update readme to a mantained and up to date bitcoin lib

shared/src/main/scala/scodec/codecs/RecoverCodec.scala, unitTests/src/test/scala/scodec/codecs/RecoverCodecTest.scala
=> Fix bug in recover encode behavior

README.md
links to the one on typelevel though.
=> updated to Scala code of conduct

shared/src/main/scala/scodec/codecs/package.scala
Fix units on a couple `bytes` codec docs.
=> Documentation Fix

shared/src/main/scala/scodec/codecs/package.scala, unitTests/src/test/scala/scodec/codecs/ListCodecTest.scala, unitTests/src/test/scala/scodec/codecs/VectorCodecTest.scala
=> Fix [list|vector]ofN codecs chunk behavior.

build.sbt
This broke the dotty community build.
=> Fix version number comparison

build.sbt, project/plugins.sbt
Rationale in https://github.com/Comcast/ip4s/pull/338.
Please speak up if this is a concern! If folks are actively using OSGi metadata, I'm happy to keep it. I'll keep this PR open for a while to give folks a chance to chime in.
=> Remove OSGi support

build.sbt
=> Switch to semantic versioning

shared/src/main/scala/scodec/codecs/ConstrainedVariableSizeCodec.scala, unitTests/shared/src/test/scala/scodec/codecs/ConstrainedVariableSizeCodecTest.scala
=> Fix sizeBound of ConstrainedVariableSizeCodec

shared/src/main/scala/scodec/Codec.scala, shared/src/main/scala/scodec/DropUnits.scala, shared/src/main/scala/scodec/InlineFoldR.scala, unitTests/shared/src/test/scala/scodec/codecs/FatCodecTest.scala, unitTests/shared/src/test/scala/scodec/codecs/HugeCodecTest.scala
=> Unroll recursive inline methods

build.sbt, shared/src/main/scala/scodec/codecs/BigIntCodec.scala, shared/src/main/scala/scodec/codecs/UnsizedBigIntCodec.scala, shared/src/main/scala/scodec/codecs/codecs.scala, unitTests/shared/src/test/scala/scodec/codecs/BigIntCodecTest.scala
=> Add codecs for BigInt
