src/main/scala/scodec/codecs/package.scala
src/test/scala/scodec/codecs/StringCodecTest.scala

I came across the need for little endian versions of the string32 codecs. I added three new codecs: string32L, ascii32L and utf8_32L. The only difference is that the string length field is encoded little endian rather than big endian.

Add little endian versions of string32, ascii32 and utf8_32.

---

README.md

Was reading through the project and noticed a few of the links to the source and examples were getting 404s.

fix a few 404ing example links

---

shared/src/main/scala/scodec/codecs/VarIntCodec.scala
shared/src/main/scala/scodec/codecs/VarLongCodec.scala
shared/src/main/scala/scodec/codecs/package.scala
shared/src/test/scala/scodec/codecs/VarIntCodecTest.scala
shared/src/test/scala/scodec/codecs/VarLongCodecTest.scala

A first sketch on a [variable length](https://en.wikipedia.org/wiki/Variable-length_quantity) implementation for ints and longs, useful as a general purpose int-packing.
The implementation has some duplicated code, but I haven't figured out a good way to abstract over this. The alternative would have been a tailrec method with some 6 or 7 parameters, which is not really better, imho.
Also, `vint` could probably be just the `vlong.xmap(...)` bit except for the `sizeBound`. Is there maybe a way to adjust the size bound, similar to `withContext` and `withToString`?
A downside of these encodings is, they work poorly with negative values. Negative ints will always have a penalty and be encoded in 5 bytes; negative longs aren't even supported in the first place.
There is a variant of this …

Add varint and varlong codecs

---

benchmark/src/main/scala/UuidBenchmark.scala
build.sbt
shared/src/main/scala/scodec/codecs/UuidCodec.scala

This provides a minor optimization to the UUID codec by avoiding going through an intermediate tuple.
I'm not sure such a minor change is justified, but this also adds a `benchmark` module that I think would be nice to have going forward.
Here are the results of the benchmark on my machine before and after the
optimizations:
Before change:
```
[info] Benchmark             Mode  Cnt  Score    Error  Units
[info] UuidBenchmark.decode  avgt  200  0.221 ±  0.008  us/op
[info] UuidBenchmark.encode  avgt  200  0.097 ±  0.001  us/op
```
After change:
```
[info] Benchmark             Mode  Cnt  Score    Error  Units
[info] UuidBenchmark.decode  avgt  200  0.196 ±  0.003  us/op
[info] UuidBenchmark.encode  avgt  200  0.088 ±  0.001  us/op
```

Minor optimizations to UUID codec

---

shared/src/main/scala/scodec/codecs/MultiplexedCodec.scala
shared/src/test/scala/scodec/codecs/MultiplexedCodecTest.scala

The infinite loop seemed to be coming from the missing "start" parameter when recursion happens
Regards, 
Olivier.

Fix #74 infinite loop for listDelimited + test

---

js/src/main/scala/scodec/Platform.scala
jvm/src/main/scala/scodec/Platform.scala
shared/src/main/scala/scodec/codecs/package.scala

Implements the changes outlined by @mpilquist [here](https://github.com/scodec/scodec/pull/76#issuecomment-135196140).
Verified on Android.

split off Charset support for JVM and JS

---

shared/src/main/scala/scodec/codecs/package.scala

It looks like the `build` method no longer exists.

Drop obsolete .build call in discriminated doc

---

shared/src/main/scala/scodec/codecs/ConditionalCodec.scala
shared/src/main/scala/scodec/codecs/package.scala
shared/src/test/scala/scodec/codecs/ConditionalCodecTest.scala

As stated on #82, the conditional codec should not evaluate the supplied codec if the condition is false. This PR changes the behavior of `ConditionalCodec` by making the `codec` parameter a 'call-by-name' and storing the evaluated result in a lazy val, thus evaluating the `codec` at most once.

Lazy Conditional Codec

---

shared/src/main/scala/scodec/codecs/package.scala
shared/src/test/scala/scodec/codecs/PackedDecimalCodecTest.scala

This way bcd-based encodings wih fewer nibbles than specified or with odd-nibble-sizes will be left-padded with 0, contrary to the pbcd codec

Add left padded pbcd codec

---

shared/src/main/scala/scodec/codecs/PaddedVarAlignedCodec.scala
shared/src/main/scala/scodec/codecs/package.scala
shared/src/test/scala/scodec/codecs/PaddedVarAlignedCodecTest.scala

Some binary protocols have variable sized payloads, but still need you to be 'aligned' on a multiplier (like 32 bits).  This codec helps get variable sized codec padded to the right length.

padded variable aligned codec

---

testkit/shared/src/main/scala/scodec/CodecSuite.scala

deprecated since Scala 2.13.0-M4
https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/package.scala#L23-L26

use Iterable instead of GenTraversable

---

shared/src/main/scala/scodec/Decoder.scala
shared/src/main/scala/scodec/Encoder.scala
shared/src/main/scala/scodec/Err.scala

In a streaming context, the typical usage involves accumulating bits and applying a codec until an error other than `Err.InsufficientBits` is encountered. This works fine unless the codec is a [choice](https://github.com/scodec/scodec/blob/e5afd2a5d95d5a110679969384dd3fa75b830f7b/shared/src/main/scala/scodec/codecs/package.scala#L1223) codec, in which case the error returned is the one from the choice applied last.
This PR introduces a composite error type, `Err.Composite`, that retains all errors for choice codecs.
This would enable streaming applications to suspend the decode operation correctly without depending on the order of choices applied.
```scala
def decodeAccumulate[F[_], A](
decoder: Decoder[A])(
bits: BitVector,
acc: List[A],
suspend: Err => Boolean)(implicit F: Sync[F]): …
```

Added Err.Composite for choice codecs

---

.travis.yml
build.sbt
project/build.properties
project/plugins.sbt
testkit/shared/src/main/scala/scodec/CodecSuite.scala
unitTests/src/test/scala/scodec/SizeBoundTest.scala

This update should let scodec to be published on scala.js 1.0
I'm not sure how releases are made, It would be nice to publish to 0.6.32 and 1.0 for a while
It includes some library updates across the board

Updates to compile under scala.js 1.0

---

shared/src/main/scala/scodec/codecs/package.scala
unitTests/src/test/scala/scodec/codecs/ListCodecTest.scala
unitTests/src/test/scala/scodec/codecs/VectorCodecTest.scala

Inspired by scodec/scodec-stream#58. I've also come up against ths same issue when decoding large messages using scodec-stream. The changes in this PR seem to solve the issue in my local project.

Fix [list|vector]ofN codecs chunk behavior.

---

README.md

The bmsg library appears to have disappeared from github. My bitcoin-scodec library is still up.

Update bitcoin-scodec link in README

---

unitTests/src/test/scala/scodec/examples/ProductsExample.scala

There seems to have been a copy-paste mistake when rewriting those tests.
`derive` is awesome by the way!

Remove the test on `derive`

---

shared/src/main/scala/scodec/codecs/VarLongCodec.scala
unitTests/src/test/scala/scodec/codecs/DiscriminatorCodecTest.scala
unitTests/src/test/scala/scodec/codecs/RecoverCodecTest.scala
unitTests/src/test/scala/scodec/codecs/VarLongCodecTest.scala

Change varlong to return a failure instead of throwing when encoding a negative value

---

unitTests/src/test/scala/scodec/examples/PcapExample.scala

Pcap file format use 24 bytes for global header. Not 28. https://tools.ietf.org/id/draft-gharris-opsawg-pcap-00.html

wrong pcap header size

---

shared/src/main/scala/scodec/DropUnits.scala

We broke scodec in Dotty's community build with https://github.com/lampepfl/dotty/pull/12261 (this was the only usage of the unintended syntax I could find). This PR backports the diff.

Use `case Any =>` instead of `case ? =>` in match type

---

README.md

Three unit test examples moved to shared and jvm directories - updating links.

Fix three broken links to examples in README.md.

---

shared/src/main/scala/scodec/codecs/VarIntCodec.scala

Two bitwise operations can be squashed into a single one.
Paranoid extra mode on, here's the bytecode before/after:
```
public long scodec$codecs$VarIntCodec$$$toPositiveLong(int);
Code:
0: iload_1
1: iconst_0
2: if_icmplt     8
5: iload_1
6: i2l
7: lreturn
8: iload_1
9: ldc           #21                 // int 2147483647
11: iand
12: i2l
13: getstatic     #23                 // Field NegativeIntSignBit:J
16: lor
17: lreturn
```
```
public long scodec$codecs$VarIntCodec$$$toPositiveLong(int);
Code:
0: iload_1
1: iconst_0
2: if_icmplt     8
5: iload_1
6: i2l
7: lreturn
8: iload_1
9: i2l
10: ldc2_w        #29                 // long 4294967295l
13: land
14: lreturn
```

More efficient long conversion for negative ints in `VarIntCodec`

---

shared/src/main/scala/scodec/codecs/VarIntCodec.scala
shared/src/main/scala/scodec/codecs/VarLongCodec.scala

Fixes #238
Express them in bits and not bytes, just as it's done in another `Codec[A]`s.

Fix bounds for `VarIntCodec`/`VarLongCodec`

---

shared/src/main/scala/scodec/codecs/VarLongCodec.scala
unitTests/shared/src/test/scala/scodec/codecs/VarLongCodecTest.scala

These days I'm revisiting all the stuff around `VarIntCodec`/`VarLongCodec` because I plan to add support for signed zig-zag encoding for a side project I'm working on (a pure Scala Kafka protocol implementation).
It draw my attention though that `VarLongCodec` doesn't support negative values. According to the original [PR](https://github.com/scodec/scodec/pull/64) :
>negative longs aren't even supported in the first place.
But I don't see a reason for not supporting them 🤔.  In fact, the implementation used in Kafka codebase supports it out-of-the-box and I can't see any argument against it in the Wikipedia link from the original PR.
Please, let me know if I'm missing something 🙏🏽

Support negative values for `VarLongCodec`

---

shared/src/main/scala/scodec/codecs/VarIntZigZagCodec.scala
shared/src/main/scala/scodec/codecs/VarLongZigZagCodec.scala
shared/src/main/scala/scodec/codecs/codecs.scala
unitTests/shared/src/test/scala/scodec/codecs/VarIntZigZagCodecTest.scala
unitTests/shared/src/test/scala/scodec/codecs/VarLongZigZagCodecTest.scala

As mentioned in #438 this PR adds missing zig-zag codecs for signed numbers.
I've cherry-picked the commit from #438 (it's absolutely necessary). Just because I'm always uncertain about the implications on merging things, I'll leave it as a draft to avoid the merge. Once #438 is approved/merged, I'll rebase this branch with main to have a clean history.

Signed zig-zag codecs for variable-length ints/longs

---

shared/src/main/scala/scodec/Codec.scala
unitTests/shared/src/test/scala/scodec/examples/AdtExample.scala

@milessabin warned me about this when I first created scodec 2.x but I had never gotten around to fixing it. The Scala 3.3.4 upgrade resulted in warnings on each such inline anonymous class so I finally decided to tackle this. Turns out this approach is more concise than the conceptually more elegant recursive inline definitions.
Before:
```
❯ find unitTests/jvm/target/ -name "*.class" | wc -l
259
❯ find unitTests/jvm/target/ -name "Derived*.class" | wc -l
71
```
After:
```
❯ find unitTests/jvm/target/ -name "*.class" | wc -l
231
❯ find unitTests/jvm/target/ -name "Derived*.class" | wc -l
53
```

Re-implement inline operations to avoid creating a new class for each invocation
